DROP FUNCTION WCISMEDDET.GET_ICD9_CODE;

CREATE OR REPLACE FUNCTION WCISMEDDET.get_ICD9_CODE(p_CD IN VARCHAR2)
RETURN VARCHAR2 IS
p_ICD9_CODE VARCHAR2(30);

BEGIN
   
        SELECT 
        CODE
        INTO p_ICD9_CODE        
        FROM
        WCISM_C.ICD9_CODE
        WHERE CODE_WITHOUT_DOT = p_CD;        
        RETURN (p_ICD9_CODE);

END;
/


GRANT EXECUTE ON WCISMEDDET.GET_ICD9_CODE TO PUBLIC;
